# Generated by Django 5.2.16 on 2026-08-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=50)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "school",
                "indexes": [
                    models.Index(fields=["name"], name="school_name_a1c686_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="unique_school_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=1)),
                ("number", models.IntegerField(default=1)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="apis.school",
                    ),
                ),
            ],
            options={
                "db_table": "classroom",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=10,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="apis.classroom",
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=10,
                    ),
                ),
                (
                    "classrooms",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="apis.classroom"
                    ),
                ),
            ],
            options={
                "db_table": "teacher",
            },
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["school", "year", "number"], name="classroom_school__bfda5b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("school", "year", "number"), name="unique_classroom_per_school"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["first_name", "last_name"], name="student_first_n_aa79c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["classroom"], name="student_classro_192208_idx"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["first_name", "last_name"], name="teacher_first_n_091085_idx"
            ),
        ),
    ]
